/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HRCompanion;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    PreparedStatement pst=null;
    ResultSet rs=null;
    public AdminForm() {
        initComponents();
                showclient();
        showregperf();
        showemplperf();
        showprojperf();
        jScrollPane1.setEnabled(false);
        jScrollPane1.setVisible(false);
        jScrollPane2.setEnabled(false);
        jScrollPane2.setVisible(false);
        jScrollPane4.setEnabled(false);
        jScrollPane4.setVisible(false);
        jScrollPane3.setEnabled(false);
        jScrollPane3.setVisible(false);
        txtid.setVisible(false);
        txtname.setVisible(false);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelExit = new javax.swing.JLabel();
        jLabelClientButton = new javax.swing.JLabel();
        jLabelPerfButton = new javax.swing.JLabel();
        jLabelManageUsers = new javax.swing.JLabel();
        txtid = new javax.swing.JLabel();
        txtname = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(980, 662));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 60, 60));

        jLabelClientButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClientButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClientButtonMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelClientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 50));

        jLabelPerfButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelPerfButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPerfButtonMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPerfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 230, 50));

        jLabelManageUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelManageUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelManageUsersMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelManageUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 230, 50));

        txtid.setBackground(new java.awt.Color(0, 0, 204));
        txtid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 60, 20));

        txtname.setBackground(new java.awt.Color(0, 0, 204));
        txtname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 120, 20));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "percent", "time", "comments", "cost"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 720, 360));

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "score"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 720, 360));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "review"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 720, 360));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "score"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 720, 360));

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 160, 190));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, 160, 190));

        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 230, 60));

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 230, 60));

        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 160, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRCompanion/images/HR admin.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 662));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public ArrayList<Client> clientlist(){
      ArrayList<Client> clientlist = new ArrayList<>();
      try{
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");          
        java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
        String query="SELECT * FROM ROOT.client_reviews";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
        Client client;
        
        while (rs.next()){
          client=new Client(0, "0","0","0",rs.getString("name"),"0","0",rs.getString("review"));
          clientlist.add(client);
        }
      }
      catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
      
      
      return clientlist;
    }
    
    
    public void showclient(){
       ArrayList<Client> list = clientlist();
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       Object[] row = new Object[2];
       for(int i=1;i<list.size();i++){
                   
           row[0]=list.get(i).getclientname();
           row[1]=list.get(i).getclientreview();
             
           model.addRow(row);
       }
      
    
    }
    
    public ArrayList<RegionalManagerPerformance> reglist(){
      ArrayList<RegionalManagerPerformance> reglist = new ArrayList<>();
      try{
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");          
        java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
        String query="SELECT * FROM ROOT.reg_perf";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
        RegionalManagerPerformance regperf;
        
        while (rs.next()){
          regperf=new RegionalManagerPerformance(rs.getInt("score"), "0",rs.getInt("leadership"),rs.getInt("communication"),rs.getInt("motivation"),rs.getInt("questionnaire"),rs.getInt("statement"),rs.getInt("id"));
          reglist.add(regperf);
        }
      }
      catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
      
      
      return reglist;
    }
    
    public void showregperf(){
       ArrayList<RegionalManagerPerformance> list = reglist();
       
       DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
       Object[] row = new Object[2];
       for(int i=1;i<list.size();i++){        
           row[0]=list.get(i).getid();        
           row[1]=list.get(i).getovscore();
             
           model.addRow(row);
       }
      
    
    }
    
    public ArrayList<EmployeePerformance> empllist(){
      ArrayList<EmployeePerformance> empllist = new ArrayList<>();
      try{
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");          
        java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
        String query="SELECT * FROM ROOT.empl_perf";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
        EmployeePerformance emplperf;
        
        while (rs.next()){
          emplperf=new EmployeePerformance(rs.getInt("score"), "1",rs.getInt("technical"),rs.getInt("productivity"),rs.getInt("deadlines"),rs.getInt("quality"),rs.getInt("teamwork"),rs.getInt("communication"),rs.getInt("improvement"),rs.getInt("id"));
          empllist.add(emplperf);
        }
      }
      catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
      
      
      return empllist;
    }
    
    public void showemplperf(){
       ArrayList<EmployeePerformance> list = empllist();
       
       DefaultTableModel model = (DefaultTableModel)jTable4.getModel();
       Object[] row = new Object[2];
       for(int i=1;i<list.size();i++){        
           row[0]=list.get(i).getid();        
           row[1]=list.get(i).getovscore();
             
           model.addRow(row);
       }
      
    
    }
    
    
    public ArrayList<ProjectPerformance> projlist(){
      ArrayList<ProjectPerformance> projlist = new ArrayList<>();
      try{
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");          
        java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
        String query="SELECT * FROM ROOT.project_perf";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
        ProjectPerformance projperf;
        
        while (rs.next()){
          projperf=new ProjectPerformance(rs.getInt("id"),0, "1","1",rs.getString("comments"),rs.getInt("cost"),rs.getInt("time"),rs.getInt("percent"));
          projlist.add(projperf);
        }
      }
      catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
      return projlist;
    }
    
    
    public void showprojperf(){
       ArrayList<ProjectPerformance> list = projlist();
       
       DefaultTableModel model = (DefaultTableModel)jTable3.getModel();
       Object[] row = new Object[5];
       for(int i=1;i<list.size();i++){        
           row[0]=list.get(i).getid();        
           row[1]=list.get(i).getpercent_of_specs_met();
           row[2]=list.get(i).gettime();
           row[3]=list.get(i).getcomments();
           row[4]=list.get(i).getcost();
             
           model.addRow(row);
       }
      
    
    }
    
    
    
    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        // TODO add your handling code here:
        LoginForm l = new LoginForm();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabelClientButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClientButtonMouseClicked
        // TODO add your handling code here:
        jScrollPane1.setEnabled(true);
        jScrollPane1.setVisible(true);
        jScrollPane2.setEnabled(false);
        jScrollPane2.setVisible(false);
        jScrollPane3.setEnabled(false);
        jScrollPane3.setVisible(false);
        jScrollPane4.setEnabled(false);
        jScrollPane4.setVisible(false);
        txtid.setVisible(false);
        txtname.setVisible(false);
    }//GEN-LAST:event_jLabelClientButtonMouseClicked

    private void jLabelPerfButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPerfButtonMouseClicked
        // TODO add your handling code here:
        jScrollPane1.setEnabled(false);
        jScrollPane1.setVisible(false);
        jScrollPane2.setEnabled(false);
        jScrollPane2.setVisible(false);
        jScrollPane3.setEnabled(false);
        jScrollPane3.setVisible(false);
        jScrollPane4.setEnabled(false);
        jScrollPane4.setVisible(false);
        txtid.setVisible(false);
        txtname.setVisible(false);
    }//GEN-LAST:event_jLabelPerfButtonMouseClicked

    private void jLabelManageUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelManageUsersMouseClicked
        // TODO add your handling code here:
        admin_cont mng = new admin_cont();
        mng.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelManageUsersMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        jScrollPane2.setEnabled(true);
        jScrollPane2.setVisible(true);
        txtid.setVisible(true);
        txtname.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        jScrollPane4.setEnabled(true);
        jScrollPane4.setVisible(true);
        txtid.setVisible(true);
        txtname.setVisible(true);
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int i = jTable2.getSelectedRow();
        TableModel model = jTable2.getModel();
        txtid.setText(model.getValueAt(i, 0).toString());
        
        try{
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");          
        java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
        String value = txtid.getText();
        String query="SELECT ONOMA FROM ROOT.PASS WHERE ID="+value;
        PreparedStatement stm=con.prepareStatement(query);
        
        rs = stm.executeQuery();
        if(rs.next()) { 
        String name = rs.getString("onoma");
        txtname.setText(name);}
        }
        catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        int i = jTable4.getSelectedRow();
        TableModel model = jTable4.getModel();
        txtid.setText(model.getValueAt(i, 0).toString());
        
        try{
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");          
        java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
        String value = txtid.getText();
        String query="SELECT ONOMA FROM ROOT.PASS WHERE ID="+value;
        PreparedStatement stm=con.prepareStatement(query);
        
        rs = stm.executeQuery();
        if(rs.next()) { 
        String name = rs.getString("onoma");
        txtname.setText(name);}
        }
        catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
    }//GEN-LAST:event_jTable4MouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        ManageLeavesForm ml = new ManageLeavesForm();
        ml.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        PromotionsForm pf = new PromotionsForm();
        pf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        jScrollPane3.setEnabled(true);
        jScrollPane3.setVisible(true);
        txtid.setVisible(true);
        txtname.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        int i = jTable3.getSelectedRow();
        TableModel model = jTable3.getModel();
        txtid.setText(model.getValueAt(i, 0).toString());
        
        try{
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");          
        java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
        String value = txtid.getText();
        String query="SELECT NAME FROM ROOT.PROJECT WHERE ID="+value;
        PreparedStatement stm=con.prepareStatement(query);
        
        rs = stm.executeQuery();
        if(rs.next()) { 
        String name = rs.getString("NAME");
        txtname.setText(name);}
        }
        catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
    }//GEN-LAST:event_jTable3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelClientButton;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelManageUsers;
    private javax.swing.JLabel jLabelPerfButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel txtid;
    private javax.swing.JLabel txtname;
    // End of variables declaration//GEN-END:variables
}
