/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HRCompanion;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class EmployeeForm extends javax.swing.JFrame {

    /**
     * Creates new form employee
     */
    PreparedStatement pst=null;
    ResultSet rs=null;
    public EmployeeForm(String username) {
        initComponents();
        jLabel3.setText(username);
        jScrollPane2.setEnabled(false);
        jScrollPane2.setVisible(false);
        showemplperf();
        txtid.setVisible(false);
        txtname.setVisible(false);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit = new javax.swing.JLabel();
        ViewPerf = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtid = new javax.swing.JLabel();
        txtname = new javax.swing.JLabel();
        ReqLeaveButton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ViewFeedBut = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 60, 60));

        ViewPerf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewPerf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewPerfMouseClicked(evt);
            }
        });
        getContentPane().add(ViewPerf, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 230, 60));

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 170, 190));

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "score"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 700, 370));

        txtid.setBackground(new java.awt.Color(0, 0, 204));
        txtid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 60, 20));

        txtname.setBackground(new java.awt.Color(0, 0, 204));
        txtname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 100, 20));

        ReqLeaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReqLeaveButtonMouseClicked(evt);
            }
        });
        getContentPane().add(ReqLeaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 230, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 110, 20));

        ViewFeedBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewFeedBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewFeedButMouseClicked(evt);
            }
        });
        getContentPane().add(ViewFeedBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 230, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRCompanion/images/Employee.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 662));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        // TODO add your handling code here:
        LoginForm l = new LoginForm();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ExitMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        jScrollPane2.setEnabled(true);
        jScrollPane2.setVisible(true);
        txtid.setVisible(true);
        txtname.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked
    
    
    public ArrayList<EmployeePerformance> empllist(){
      ArrayList<EmployeePerformance> empllist = new ArrayList<>();
      try{
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");          
        java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
        String query="SELECT * FROM ROOT.empl_perf";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
        EmployeePerformance emplperf;
        
        while (rs.next()){
          emplperf=new EmployeePerformance(rs.getInt("score"), "1",rs.getInt("technical"),rs.getInt("productivity"),rs.getInt("deadlines"),rs.getInt("quality"),rs.getInt("teamwork"),rs.getInt("communication"),rs.getInt("improvement"),rs.getInt("id"));
          empllist.add(emplperf);
        }
      }
      catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
      
      
      return empllist;
    }
    
    public void showemplperf(){
       ArrayList<EmployeePerformance> list = empllist();
       
       DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
       Object[] row = new Object[2];
       for(int i=1;i<list.size();i++){        
           row[0]=list.get(i).getid();        
           row[1]=list.get(i).getovscore();
             
           model.addRow(row);
       }
      
    
    }
    
    
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int i = jTable2.getSelectedRow();
        TableModel model = jTable2.getModel();
        txtid.setText(model.getValueAt(i, 0).toString());

        try{
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
            String value = txtid.getText();
            String query="SELECT ONOMA FROM ROOT.PASS WHERE ID="+value;
            PreparedStatement stm=con.prepareStatement(query);

            rs = stm.executeQuery();
            if(rs.next()) {
                String name = rs.getString("onoma");
                txtname.setText(name);}
        }
        catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
    }//GEN-LAST:event_jTable2MouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void ViewPerfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewPerfMouseClicked
        // TODO add your handling code here:
        jScrollPane2.setEnabled(false);
        jScrollPane2.setVisible(false);
        txtid.setVisible(false);
        txtname.setVisible(false);
    }//GEN-LAST:event_ViewPerfMouseClicked

    private void ReqLeaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReqLeaveButtonMouseClicked
        // TODO add your handling code here:
        RequestLeaveForm rl = new RequestLeaveForm(jLabel3.getText());
        rl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ReqLeaveButtonMouseClicked

    private void ViewFeedButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewFeedButMouseClicked
        // TODO add your handling code here:
        ViewFeedbackForm vf = new ViewFeedbackForm(jLabel3.getText());
        vf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ViewFeedButMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeForm("0").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel ReqLeaveButton;
    private javax.swing.JLabel ViewFeedBut;
    private javax.swing.JLabel ViewPerf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel txtid;
    private javax.swing.JLabel txtname;
    // End of variables declaration//GEN-END:variables
}
