/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HRCompanion;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author themi
 */
public class GeneralManagerForm extends javax.swing.JFrame {

    /**
     * Creates new form GeneralManager
     */
    PreparedStatement pst=null;
    ResultSet rs=null;
    public GeneralManagerForm(String username) {
        initComponents();
        jScrollPane1.setEnabled(false);
        jScrollPane1.setVisible(false);
        showclient();
        showregperf();
        showemplperf();
        showprojperf();
        jLabel4.setText(username);
        jScrollPane2.setEnabled(false);
        jScrollPane2.setVisible(false);
        jScrollPane3.setEnabled(false);
        jScrollPane3.setVisible(false);
        jScrollPane4.setEnabled(false);
        jScrollPane4.setVisible(false);
        txtid.setVisible(false);
        txtname.setVisible(false);
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelExit = new javax.swing.JLabel();
        jLabelClientButton = new javax.swing.JLabel();
        jLabelViewPerfButton = new javax.swing.JLabel();
        Rate = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtid = new javax.swing.JLabel();
        txtname = new javax.swing.JLabel();
        ReqLeaveBut = new javax.swing.JLabel();
        ReqMeetBut = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        GiveFeedBut = new javax.swing.JLabel();
        ViewFeedBut = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 70, 60));

        jLabelClientButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClientButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClientButtonMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelClientButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 230, 50));

        jLabelViewPerfButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelViewPerfButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelViewPerfButtonMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelViewPerfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 230, 50));

        Rate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Rate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RateMouseClicked(evt);
            }
        });
        getContentPane().add(Rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 230, 60));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "percent", "time", "comments", "cost"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 700, 370));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "review"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 700, 370));

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "score"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 700, 370));

        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "score"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 700, 370));

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 170, 190));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 160, 190));

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 170, 190));

        txtid.setBackground(new java.awt.Color(0, 0, 204));
        txtid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 50, 20));

        txtname.setBackground(new java.awt.Color(0, 0, 204));
        txtname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 130, 20));

        ReqLeaveBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReqLeaveBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReqLeaveButMouseClicked(evt);
            }
        });
        getContentPane().add(ReqLeaveBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 230, 60));

        ReqMeetBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReqMeetBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReqMeetButMouseClicked(evt);
            }
        });
        getContentPane().add(ReqMeetBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 230, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 110, 20));

        GiveFeedBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GiveFeedBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GiveFeedButMouseClicked(evt);
            }
        });
        getContentPane().add(GiveFeedBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 230, 60));

        ViewFeedBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewFeedBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewFeedButMouseClicked(evt);
            }
        });
        getContentPane().add(ViewFeedBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 230, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRCompanion/images/General.jpg"))); // NOI18N
        jLabel1.setName(""); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 662));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public ArrayList<Client> clientlist(){
      ArrayList<Client> clientlist = new ArrayList<>();
      try{
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");          
        java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
        String query="SELECT * FROM ROOT.client_reviews";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
        Client client;
        
        while (rs.next()){
          client=new Client(0, "0","0","0",rs.getString("name"),"0","0",rs.getString("review"));
          clientlist.add(client);
        }
      }
      catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
      
      
      return clientlist;
    }

    public void showclient(){
       ArrayList<Client> list = clientlist();
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       Object[] row = new Object[2];
       for(int i=1;i<list.size();i++){
                   
           row[0]=list.get(i).getclientname();
           row[1]=list.get(i).getclientreview();
             
           model.addRow(row);
       }
      
    
    }

    
    
    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        // TODO add your handling code here:
        LoginForm l = new LoginForm();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabelClientButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClientButtonMouseClicked
        // TODO add your handling code here:
        jScrollPane1.setEnabled(true);
        jScrollPane1.setVisible(true);
        jScrollPane2.setEnabled(false);
        jScrollPane2.setVisible(false);
        jScrollPane3.setEnabled(false);
        jScrollPane3.setVisible(false);
        jScrollPane4.setEnabled(false);
        jScrollPane4.setVisible(false);
        txtid.setVisible(false);
        txtname.setVisible(false);
    }//GEN-LAST:event_jLabelClientButtonMouseClicked

    private void jLabelViewPerfButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelViewPerfButtonMouseClicked
        // TODO add your handling code here:
        jScrollPane1.setEnabled(false);
        jScrollPane1.setVisible(false);
        jScrollPane2.setEnabled(false);
        jScrollPane2.setVisible(false);
        jScrollPane3.setEnabled(false);
        jScrollPane3.setVisible(false);
        jScrollPane4.setEnabled(false);
        jScrollPane4.setVisible(false);
        txtid.setVisible(false);
        txtname.setVisible(false);
        
    }//GEN-LAST:event_jLabelViewPerfButtonMouseClicked

    private void RateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RateMouseClicked
        // TODO add your handling code here:
        RateRegForm r = new RateRegForm();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RateMouseClicked
    
    
    public ArrayList<RegionalManagerPerformance> reglist(){
      ArrayList<RegionalManagerPerformance> reglist = new ArrayList<>();
      try{
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");          
        java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
        String query="SELECT * FROM ROOT.reg_perf";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
        RegionalManagerPerformance regperf;
        
        while (rs.next()){
          regperf=new RegionalManagerPerformance(rs.getInt("score"), "0",rs.getInt("leadership"),rs.getInt("communication"),rs.getInt("motivation"),rs.getInt("questionnaire"),rs.getInt("statement"),rs.getInt("id"));
          reglist.add(regperf);
        }
      }
      catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
      
      
      return reglist;
    }
    
    public void showregperf(){
       ArrayList<RegionalManagerPerformance> list = reglist();
       
       DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
       Object[] row = new Object[2];
       for(int i=1;i<list.size();i++){        
           row[0]=list.get(i).getid();        
           row[1]=list.get(i).getovscore();
             
           model.addRow(row);
       }
      
    
    }
    
    public ArrayList<EmployeePerformance> empllist(){
      ArrayList<EmployeePerformance> empllist = new ArrayList<>();
      try{
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");          
        java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
        String query="SELECT * FROM ROOT.empl_perf";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
        EmployeePerformance emplperf;
        
        while (rs.next()){
          emplperf=new EmployeePerformance(rs.getInt("score"), "1",rs.getInt("technical"),rs.getInt("productivity"),rs.getInt("deadlines"),rs.getInt("quality"),rs.getInt("teamwork"),rs.getInt("communication"),rs.getInt("improvement"),rs.getInt("id"));
          empllist.add(emplperf);
        }
      }
      catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
      
      
      return empllist;
    }
    
    public void showemplperf(){
       ArrayList<EmployeePerformance> list = empllist();
       
       DefaultTableModel model = (DefaultTableModel)jTable3.getModel();
       Object[] row = new Object[2];
       for(int i=1;i<list.size();i++){        
           row[0]=list.get(i).getid();        
           row[1]=list.get(i).getovscore();
             
           model.addRow(row);
       }
      
    
    }
    
    
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int i = jTable2.getSelectedRow();
        TableModel model = jTable2.getModel();
        txtid.setText(model.getValueAt(i, 0).toString());

        try{
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
            String value = txtid.getText();
            String query="SELECT ONOMA FROM ROOT.PASS WHERE ID="+value;
            PreparedStatement stm=con.prepareStatement(query);

            rs = stm.executeQuery();
            if(rs.next()) {
                String name = rs.getString("onoma");
                txtname.setText(name);}
        }
        catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
    }//GEN-LAST:event_jTable2MouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        jScrollPane2.setEnabled(true);
        jScrollPane2.setVisible(true);
        txtid.setVisible(true);
        txtname.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        jScrollPane3.setEnabled(true);
        jScrollPane3.setVisible(true);
        txtid.setVisible(true);
        txtname.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        int i = jTable3.getSelectedRow();
        TableModel model = jTable3.getModel();
        txtid.setText(model.getValueAt(i, 0).toString());

        try{
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
            String value = txtid.getText();
            String query="SELECT ONOMA FROM ROOT.PASS WHERE ID="+value;
            PreparedStatement stm=con.prepareStatement(query);

            rs = stm.executeQuery();
            if(rs.next()) {
                String name = rs.getString("onoma");
                txtname.setText(name);}
        }
        catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
    }//GEN-LAST:event_jTable3MouseClicked

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void ReqLeaveButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReqLeaveButMouseClicked
        // TODO add your handling code here:
        RequestLeaveForm rl = new RequestLeaveForm(jLabel4.getText());
        rl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ReqLeaveButMouseClicked

    private void ReqMeetButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReqMeetButMouseClicked
        // TODO add your handling code here:
        RequestMeetingForm rm = new RequestMeetingForm();
        rm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ReqMeetButMouseClicked

    private void GiveFeedButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GiveFeedButMouseClicked
        // TODO add your handling code here:
        GiveFeedbackForm gf = new GiveFeedbackForm(jLabel4.getText());
        gf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GiveFeedButMouseClicked

    private void ViewFeedButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewFeedButMouseClicked
        // TODO add your handling code here:
        ViewFeedbackForm vf = new ViewFeedbackForm(jLabel4.getText());
        vf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ViewFeedButMouseClicked

    
        public ArrayList<ProjectPerformance> projlist(){
      ArrayList<ProjectPerformance> projlist = new ArrayList<>();
      try{
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");          
        java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
        String query="SELECT * FROM ROOT.project_perf";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
        ProjectPerformance projperf;
        
        while (rs.next()){
          projperf=new ProjectPerformance(rs.getInt("id"),0, "1","1",rs.getString("comments"),rs.getInt("cost"),rs.getInt("time"),rs.getInt("percent"));
          projlist.add(projperf);
        }
      }
      catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
      return projlist;
    }
    
    
    public void showprojperf(){
       ArrayList<ProjectPerformance> list = projlist();
       
       DefaultTableModel model = (DefaultTableModel)jTable4.getModel();
       Object[] row = new Object[5];
       for(int i=1;i<list.size();i++){        
           row[0]=list.get(i).getid();        
           row[1]=list.get(i).getpercent_of_specs_met();
           row[2]=list.get(i).gettime();
           row[3]=list.get(i).getcomments();
           row[4]=list.get(i).getcost();
             
           model.addRow(row);
       }
      
    
    }
    
    
    
    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        int i = jTable4.getSelectedRow();
        TableModel model = jTable4.getModel();
        txtid.setText(model.getValueAt(i, 0).toString());

        try{
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
            String value = txtid.getText();
            String query="SELECT NAME FROM ROOT.PROJECT WHERE ID="+value;
            PreparedStatement stm=con.prepareStatement(query);

            rs = stm.executeQuery();
            if(rs.next()) {
                String name = rs.getString("NAME");
                txtname.setText(name);}
        }
        catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
    }//GEN-LAST:event_jTable4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        jScrollPane4.setEnabled(true);
        jScrollPane4.setVisible(true);
        txtid.setVisible(true);
        txtname.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralManagerForm("0").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GiveFeedBut;
    private javax.swing.JLabel Rate;
    private javax.swing.JLabel ReqLeaveBut;
    private javax.swing.JLabel ReqMeetBut;
    private javax.swing.JLabel ViewFeedBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelClientButton;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelViewPerfButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel txtid;
    private javax.swing.JLabel txtname;
    // End of variables declaration//GEN-END:variables
}
