/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HRCompanion;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class RegionalManagerForm extends javax.swing.JFrame {

    /**
     * Creates new form RegionalManager
     */
    PreparedStatement pst=null;
    ResultSet rs=null;
    public RegionalManagerForm(String username) {
        initComponents();
        jScrollPane2.setEnabled(false);
        jScrollPane2.setVisible(false);
        jScrollPane3.setEnabled(false);
        jScrollPane3.setVisible(false);
        txtid.setVisible(false);
        txtname.setVisible(false);
        jLabel2.setText(username);
        showregperf();
        showemplperf();
    }

    private RegionalManagerForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelExit = new javax.swing.JLabel();
        jLabelViewFeedButton = new javax.swing.JLabel();
        jLabelViewPerfButton = new javax.swing.JLabel();
        Feed = new javax.swing.JLabel();
        Rate = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        ReqLeaveBut = new javax.swing.JLabel();
        ReqMeetBut = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JLabel();
        txtname = new javax.swing.JLabel();
        ViewReg = new javax.swing.JLabel();
        ViewEmpl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(980, 662));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 60, 60));

        jLabelViewFeedButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelViewFeedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelViewFeedButtonMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelViewFeedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 230, 50));

        jLabelViewPerfButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelViewPerfButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelViewPerfButtonMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelViewPerfButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 230, 50));

        Feed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Feed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FeedMouseClicked(evt);
            }
        });
        getContentPane().add(Feed, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 230, 50));

        Rate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Rate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RateMouseClicked(evt);
            }
        });
        getContentPane().add(Rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 230, 60));

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "score"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 700, 370));

        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "score"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 700, 370));

        ReqLeaveBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReqLeaveBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReqLeaveButMouseClicked(evt);
            }
        });
        getContentPane().add(ReqLeaveBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 230, 60));

        ReqMeetBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReqMeetBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReqMeetButMouseClicked(evt);
            }
        });
        getContentPane().add(ReqMeetBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 110, 20));

        txtid.setBackground(new java.awt.Color(0, 0, 204));
        txtid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 60, 20));

        txtname.setBackground(new java.awt.Color(0, 0, 204));
        txtname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 110, 20));

        ViewReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewRegMouseClicked(evt);
            }
        });
        getContentPane().add(ViewReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 160, 190));

        ViewEmpl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewEmpl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewEmplMouseClicked(evt);
            }
        });
        getContentPane().add(ViewEmpl, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 170, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRCompanion/images/Regional_1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 662));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        // TODO add your handling code here:
        LoginForm l = new LoginForm();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabelViewFeedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelViewFeedButtonMouseClicked
        // TODO add your handling code here:
        ViewFeedbackForm vf = new ViewFeedbackForm(jLabel2.getText());
        vf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelViewFeedButtonMouseClicked

    private void jLabelViewPerfButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelViewPerfButtonMouseClicked
        // TODO add your handling code here:
        jScrollPane2.setEnabled(false);
        jScrollPane2.setVisible(false);
        jScrollPane3.setEnabled(false);
        jScrollPane3.setVisible(false);
        txtid.setVisible(false);
        txtname.setVisible(false);
        
    }//GEN-LAST:event_jLabelViewPerfButtonMouseClicked

    private void FeedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedMouseClicked
        // TODO add your handling code here:
        GiveFeedbackForm gv = new GiveFeedbackForm(jLabel2.getText());
        gv.setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_FeedMouseClicked

    private void RateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RateMouseClicked
        // TODO add your handling code here:
        RateEmplForm er = new RateEmplForm();
        er.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RateMouseClicked

    private void ReqLeaveButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReqLeaveButMouseClicked
       // TODO add your handling code here:
        RequestLeaveForm rl = new RequestLeaveForm(jLabel2.getText());
        rl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ReqLeaveButMouseClicked

    private void ReqMeetButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReqMeetButMouseClicked
        // TODO add your handling code here:
        RequestMeetingForm rm = new RequestMeetingForm();
        rm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ReqMeetButMouseClicked
    
    
    public ArrayList<RegionalManagerPerformance> reglist(){
      ArrayList<RegionalManagerPerformance> reglist = new ArrayList<>();
      try{
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");          
        java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
        String query="SELECT * FROM ROOT.reg_perf";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
        RegionalManagerPerformance regperf;
        
        while (rs.next()){
          regperf=new RegionalManagerPerformance(rs.getInt("score"), "0",rs.getInt("leadership"),rs.getInt("communication"),rs.getInt("motivation"),rs.getInt("questionnaire"),rs.getInt("statement"),rs.getInt("id"));
          reglist.add(regperf);
        }
      }
      catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
      
      
      return reglist;
    }
    
    public void showregperf(){
       ArrayList<RegionalManagerPerformance> list = reglist();
       
       DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
       Object[] row = new Object[2];
       for(int i=1;i<list.size();i++){        
           row[0]=list.get(i).getid();        
           row[1]=list.get(i).getovscore();
             
           model.addRow(row);
       }
    }
    
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int i = jTable2.getSelectedRow();
        TableModel model = jTable2.getModel();
        txtid.setText(model.getValueAt(i, 0).toString());

        try{
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
            String value = txtid.getText();
            String query="SELECT ONOMA FROM ROOT.PASS WHERE ID="+value;
            PreparedStatement stm=con.prepareStatement(query);

            rs = stm.executeQuery();
            if(rs.next()) {
                String name = rs.getString("onoma");
                txtname.setText(name);}
        }
        catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
    }//GEN-LAST:event_jTable2MouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void ViewRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewRegMouseClicked
        // TODO add your handling code here:
        jScrollPane2.setEnabled(true);
        jScrollPane2.setVisible(true);
        txtid.setVisible(true);
        txtname.setVisible(true);
    }//GEN-LAST:event_ViewRegMouseClicked
    
    
    public ArrayList<EmployeePerformance> empllist(){
      ArrayList<EmployeePerformance> empllist = new ArrayList<>();
      try{
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");          
        java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
        String query="SELECT * FROM ROOT.empl_perf";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
        EmployeePerformance emplperf;
        
        while (rs.next()){
          emplperf=new EmployeePerformance(rs.getInt("score"), "1",rs.getInt("technical"),rs.getInt("productivity"),rs.getInt("deadlines"),rs.getInt("quality"),rs.getInt("teamwork"),rs.getInt("communication"),rs.getInt("improvement"),rs.getInt("id"));
          empllist.add(emplperf);
        }
      }
      catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
      
      
      return empllist;
    }
    
    public void showemplperf(){
       ArrayList<EmployeePerformance> list = empllist();
       
       DefaultTableModel model = (DefaultTableModel)jTable3.getModel();
       Object[] row = new Object[2];
       for(int i=1;i<list.size();i++){        
           row[0]=list.get(i).getid();        
           row[1]=list.get(i).getovscore();
             
           model.addRow(row);
       }
      
    
    }
    
    
    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        int i = jTable3.getSelectedRow();
        TableModel model = jTable3.getModel();
        txtid.setText(model.getValueAt(i, 0).toString());

        try{
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:derby:.\\databases\\Login", "root", "1234");
            String value = txtid.getText();
            String query="SELECT ONOMA FROM ROOT.PASS WHERE ID="+value;
            PreparedStatement stm=con.prepareStatement(query);

            rs = stm.executeQuery();
            if(rs.next()) {
                String name = rs.getString("onoma");
                txtname.setText(name);}
        }
        catch(Exception ex){JOptionPane.showMessageDialog(this, ex.getMessage());}
    }//GEN-LAST:event_jTable3MouseClicked

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void ViewEmplMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewEmplMouseClicked
        // TODO add your handling code here:
        jScrollPane3.setEnabled(true);
        jScrollPane3.setVisible(true);
        txtid.setVisible(true);
        txtname.setVisible(true);
    }//GEN-LAST:event_ViewEmplMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegionalManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegionalManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegionalManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegionalManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegionalManagerForm("0").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Feed;
    private javax.swing.JLabel Rate;
    private javax.swing.JLabel ReqLeaveBut;
    private javax.swing.JLabel ReqMeetBut;
    private javax.swing.JLabel ViewEmpl;
    private javax.swing.JLabel ViewReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelViewFeedButton;
    private javax.swing.JLabel jLabelViewPerfButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel txtid;
    private javax.swing.JLabel txtname;
    // End of variables declaration//GEN-END:variables
}
